# Generated by Django 2.1.4 on 2019-01-20 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=30, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('street_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_branch_address', models.CharField(blank=True, max_length=15, null=True)),
                ('street_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_hq_address', models.CharField(blank=True, max_length=15, null=True)),
                ('street_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_home_address', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='subscriptions',
            field=models.ManyToManyField(to='core.Subscription'),
        ),
        migrations.AddField(
            model_name='business',
            name='customers',
            field=models.ManyToManyField(to='core.Customer'),
        ),
    ]
