# Generated by Django 2.1.4 on 2019-02-25 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('username', models.CharField(default='', max_length=30, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('staff', models.BooleanField(default=False)),
                ('customer', models.BooleanField(default=False)),
                ('business', models.BooleanField(default=False)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('business_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('street_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_branch_address', models.CharField(blank=True, max_length=15, null=True)),
                ('street_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_hq_address', models.CharField(blank=True, max_length=15, null=True)),
                ('street_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_home_address', models.CharField(blank=True, max_length=15, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ActiveRedeemables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=2550)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(default='example@email.com', max_length=255, unique=True)),
                ('username', models.CharField(default='username', max_length=30, unique=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('user_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('nmi_login', models.CharField(default='nmi', max_length=30, unique=True)),
                ('nmi_password', models.CharField(default='nmi', max_length=30, unique=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('street_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_branch_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_branch_address', models.CharField(blank=True, max_length=15, null=True)),
                ('street_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_hq_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_hq_address', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(default='', max_length=30, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(default='', max_length=15)),
                ('email', models.EmailField(default='', max_length=255, unique=True)),
                ('user_api_key', models.CharField(blank=True, max_length=1000, null=True)),
                ('active', models.BooleanField(default=False)),
                ('street_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('apt_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('city_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('state_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country_home_address', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_home_address', models.CharField(blank=True, max_length=15, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryRedeemables',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('set_expiration', models.DateTimeField(blank=True, null=True)),
                ('method_redeemed', models.BooleanField(default=False)),
                ('benefit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Benefit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=2550)),
                ('amount', models.IntegerField(default=1)),
                ('monthly_recurring', models.BooleanField(default=False)),
                ('benefits', models.ManyToManyField(related_name='subscriptions', to='core.Benefit')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business')),
            ],
        ),
        migrations.AddField(
            model_name='historyredeemables',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubscriptionPlan'),
        ),
        migrations.AddField(
            model_name='benefit',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Business'),
        ),
        migrations.AddField(
            model_name='activeredeemables',
            name='benefit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Benefit'),
        ),
        migrations.AddField(
            model_name='activeredeemables',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer'),
        ),
        migrations.AddField(
            model_name='activeredeemables',
            name='subscription_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.SubscriptionPlan'),
        ),
    ]
