# Generated by Django 2.1.4 on 2019-02-26 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='business_FK',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
