# Generated by Django 2.1.4 on 2019-01-29 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='customer_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='customer_name',
            new_name='name',
        ),
    ]
