# Generated by Django 2.1.4 on 2019-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190227_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='customer_subscriptions', to='core.SubscriptionPlan'),
        ),
    ]
