# Generated by Django 2.1.4 on 2019-03-05 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_customer_subscriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
