# Generated by Django 2.1.4 on 2019-02-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20190220_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='first_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_exp_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='credit_card_number',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='customer',
            name='business_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Business'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
